development: &development
  adapter: postgresql
  encoding: unicode
  database: test_app_development
  host: 127.0.0.1
  port: 5432
  pool: 5
  username: docker
  password: docker

test:
  <<: *development
  host: 127.0.0.1
  username: docker
  database: docker
  password: docker

production:
  <<: *development
  host: 127.0.0.1
  username: docker
  database: test_app
  password: docker
