development: &development
  adapter: postgresql
  encoding: unicode
  database: test_app_development
  host: localhost
  pool: 5
  username: docker
  password: docker

test:
  <<: *development
  host: localhost
  username: docker
  database: docker

